### ISSUE TITLE
Corpus Creation Errors

### ISSUE THREAD

**Issue by TWHarr** [fitnr/twitter_markov#13]
Python v3.6.5

Trying to create a corpus, getting an error with wordfilter. 

```
Traceback (most recent call last):
  File "/Users/timharrison/.pyenv/versions/3.6.5/bin/twittermarkov", line 11, in <module>
    load_entry_point('twitter-markov==0.5.0', 'console_scripts', 'twittermarkov')()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twitter_markov-0.5.0-py3.6.egg/twitter_markov/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twitter_markov-0.5.0-py3.6.egg/twitter_markov/twitter_markov.py", line 24, in <module>
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/wordfilter/__init__.py", line 6, in <module>
    from .wordfilter import blacklisted, add_words, clear_list, Wordfilter
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/wordfilter/wordfilter.py", line 52, in <module>
    _module_instance = Wordfilter()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/wordfilter/wordfilter.py", line 29, in __init__
    self.blacklist = [s.lower() for s in json.loads(data, 'r')]
TypeError: loads() takes 1 positional argument but 2 were given
```

I saw in another issue that updating wordfilter was the solution to this, but after doing that, i get this:

```
Traceback (most recent call last):
  File "/Users/timharrison/.pyenv/versions/3.6.5/bin/twittermarkov", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wordfilter<0.2.0pyyaml,>=0.1.8' distribution was not found and is required by twitter-markov
```

Which makes sense as wordfilter is at 0.2.6.2. 

Any way to resolve these issues and get a corpus going?

**Comment by fitnr** [comment]
There was a missing comma in `setup.py`. If you download the package and install with `python setup.py install` everything should work. I'll make an update on pypi soon.

**Comment by TWHarr** [comment]
Thanks for check this so quickly! I downloaded and installed the new package but I'm still having the same errors. 

On wordfilter 0.1.8 or 0.1.9, i get 

'''
Tim-Harrison:pydohimbot timharrison$ twittermarkov corpus tweets.csv
Traceback (most recent call last):
  File "/Users/timharrison/.pyenv/versions/3.6.5/bin/twittermarkov", line 11, in <module>
    load_entry_point('twitter-markov==0.5.0', 'console_scripts', 'twittermarkov')()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twitter_markov-0.5.0-py3.6.egg/twitter_markov/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twitter_markov-0.5.0-py3.6.egg/twitter_markov/twitter_markov.py", line 24, in <module>
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/wordfilter/__init__.py", line 3, in <module>
    from .wordfilter import blacklisted, add_words, clear_list, Wordfilter
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/wordfilter/wordfilter.py", line 45, in <module>
    _module_instance = Wordfilter()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/wordfilter/wordfilter.py", line 29, in __init__
    self.blacklist = [s.lower() for s in json.loads(data, 'r')]
TypeError: loads() takes 1 positional argument but 2 were given
'''

and on the latest wordfilter (0.2.6.2) i'm getting (presumably as intended):

'''
Tim-Harrison:pydohimbot timharrison$ twittermarkov corpus tweets.csv
Traceback (most recent call last):
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wordfilter 0.2.6.2 (/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages), Requirement.parse('wordfilter<0.2.0,>=0.1.8'), {'twitter-markov'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/timharrison/.pyenv/versions/3.6.5/bin/twittermarkov", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/timharrison/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wordfilter<0.2.0,>=0.1.8' distribution was not found and is required by twitter-markov
'''

**Comment by fitnr** [comment]
you're in python version hell. just manually change `wordfilter<0.2.0,>=0.1.8'` in setup.py to `'wordfilter==0.2.6.2'`

**Comment by fitnr** [comment]
uploaded a new version (0.5.1), which should resolve more of these issues.

**Comment by TWHarr** [comment]
I often find myself in version hell. Thanks for helping with this, humming along nicely now. :)
