### ISSUE TITLE
KeyError: 'text'

### ISSUE THREAD

**Issue by BrekiTomasson** [fitnr/twitter_markov#2]
Any ideas why this is happening?

```
pi@raspberrypi:~/ThePostmodern $ twittermarkov corpus ./data/tweets.txt
Reading ./data/tweets.txt
Traceback (most recent call last):
  File "/usr/local/bin/twittermarkov", line 9, in <module>
    load_entry_point('twitter-markov==0.4.2', 'console_scripts', 'twittermarkov')()
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 77, in main
    func(argdict)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 100, in learn_func
    sys.stdout.writelines(tweets)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 96, in <genexpr>
    tweets = ((tweet.replace('\n', ' ') + '\n') for tweet in gen)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/checking.py", line 50, in generator
    for status in tweets:
  File "/usr/local/lib/python2.7/dist-packages/twitter_bot_utils/archive.py", line 34, in read_csv
    tweet['text'] = unicode(tweet['text'], 'utf-8')
KeyError: 'text'
```

**Comment by BrekiTomasson** [comment]
For reference, I'm trying to read a plaintext file with one sentence per line to buiild a corpus, not a CSV file. I understood that was supposed to work?

**Comment by fitnr** [comment]
Right now it's only expecting a twitter dot com archive csv. As a workaround for now, try adding "text" as a header on the first row of your file. This should make it enough of a CSV for import to work.

I'll think about the best way to extend the functionality and push an update soon.

**Comment by fitnr** [comment]
Added support for plain text files with v0.4.3. Just use the new flag:
```
twittermarkov corpus --one-per-line ./data/tweets.txt
```
