### ISSUE TITLE
writelines() argument must be a sequence of strings

### ISSUE THREAD

**Issue by BrekiTomasson** [fitnr/twitter_markov#3]
First of all, thanks for the quick answer in #2 - it's absolutely gotten me one step closer! But now I'm having this problem instead:

```
pi@raspberrypi:~/ThePostmodern $ twittermarkov corpus --one-per-line ./data/tweets.txt
Reading ./data/tweets.txt
Traceback (most recent call last):
  File "/usr/local/bin/twittermarkov", line 9, in <module>
    load_entry_point('twitter-markov==0.4.3', 'console_scripts', 'twittermarkov')()
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 70, in main
    func(argdict)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 98, in learn_func
    sys.stdout.writelines(tweets)
TypeError: writelines() argument must be a sequence of strings
```

I first assumed there was something problem with my tweets.txt file, but there doesn't seem to be. The linebreaks are all in UNIX format, there's just plain text without any fancy characters that could be breaking anything... Any ideas?

**Comment by fitnr** [comment]
What version of Python are you using? (`python -V`)

**Comment by fitnr** [comment]
By the way, if your file of tweets is what you want to use as a corpus, you can skip to just tweeting:

````bash
twittermarkov tweet --scren_name MyScreenName_ebooks --corpus ./data/tweets.txt -c bots.yaml
````

The corpus command is just for filtering tweets in an archive.

**Comment by BrekiTomasson** [comment]
Python 2.7.9. And yeah, that actually worked out, and it's posting for me now. I didn't realize I could skip the stage of generating the corpus.

**Comment by wiseman** [comment]
I'm getting the same error. Was the cause of this ever determined?

**Comment by wiseman** [comment]
Looks like it's a Python 2 issue; If you run with Python 3 it works.

**Comment by bottitytto** [comment]
I am getting this error on Python versions 2.7.9, 3.4.2, 3.5.3, and 3.6.0.

**Comment by gyaresu** [comment]
3.6 didn't work, but 3.4 did.

```
λ twittermarkov
Traceback (most recent call last):
  File "/Users/gyaresu/miniconda2/envs/markov/bin/twittermarkov", line 7, in <module>
    from twitter_markov.cli import main
  File "/Users/gyaresu/miniconda2/envs/markov/lib/python3.6/site-packages/twitter_markov/__init__.py", line 17, in <module>
    from .twitter_markov import TwitterMarkov
  File "/Users/gyaresu/miniconda2/envs/markov/lib/python3.6/site-packages/twitter_markov/twitter_markov.py", line 24, in <module>
    from wordfilter import Wordfilter
  File "/Users/gyaresu/miniconda2/envs/markov/lib/python3.6/site-packages/wordfilter/__init__.py", line 6, in <module>
    from .wordfilter import blacklisted, add_words, clear_list, Wordfilter
  File "/Users/gyaresu/miniconda2/envs/markov/lib/python3.6/site-packages/wordfilter/wordfilter.py", line 52, in <module>
    _module_instance = Wordfilter()
  File "/Users/gyaresu/miniconda2/envs/markov/lib/python3.6/site-packages/wordfilter/wordfilter.py", line 29, in __init__
    self.blacklist = [s.lower() for s in json.loads(data, 'r')]
TypeError: loads() takes 1 positional argument but 2 were given
```

**Comment by fitnr** [comment]
@gyaresu the error here is in the wordfilter package. Try `pip install -U wordfilter`.
