### ISSUE TITLE
Script doesn't recognize bots.yaml

### ISSUE THREAD

**Issue by andrew-wilcox** [fitnr/twitter_markov#9]
http://pastebin.com/raw/Dc65uTFx - bots.yaml, in the same directory that I'm running the command from

The command I'm running (I've tried a few variants, but):
twittermarkov -c /usr/local/bin/twitterbots/pastebin_ebooks/bots.yaml tweet
Traceback (most recent call last):
  File "/usr/local/bin/twittermarkov", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 73, in main
    func(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 80, in tweet_func
    tm = TwitterMarkov(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/twitter_markov.py", line 49, in __init__
    self.api = tbu.API(screen_name=screen_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twitter_bot_utils/api.py", line 83, in __init__
    raise ValueError("Incomplete config. Missing {}".format(missing))
ValueError: Incomplete config. Missing ['consumer_key', 'consumer_secret', 'key', 'secret']

Which I'm taking to mean that it's not understanding my bots.yaml file correctly. Perhaps I'm misunderstanding how to format the command, though.

Thanks!

**Comment by andrew-wilcox** [comment]
Adding the -u [username] flag fixed my issues. Thanks!
